name: multicast_dns_error_repo
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  network_tools: ^3.0.0+3

dev_dependencies:
  lints: ^2.0.1
  test: ^1.16.0